### ISSUE TITLE
date/time format

### ISSUE THREAD

**Issue by sanobertin** [MatteoGisondi/Concordia-Schedule-Export#3]
Not much of an issue, but a suggestion instead. 
On line 51 of export.py, the code would be break if HTML calendar is already in 24hr mode. 
This code could fix it >> #**in_time = datetime.strptime(time, "%H:%M%S")**

Ref: https://docs.python.org/3/library/datetime.html?highlight=datetime%20strptime#strftime-strptime-behavior

**Comment by MatteoGisondi** [comment]
Unfortunately this format changes all the time. So sometimes it works and others it doesn't.

No use in future proofing something that breaks intermittently anyway.

**Comment by sanobertin** [comment]
.
